version: "1"
services:
  webserver:
    build: ./php-apache/
    container_name: webserver
    ports:
      - 0.0.0.0:8080:80
    volumes:
      - ../src:/var/www/html
  db:
    image: mysql:latest
    container_name: cms-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 0.0.0.0:5051:3306
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER_ID}"
      MYSQL_PASSWORD: "${DB_USER_PASSWORD}"
    volumes:
      - ./mysql:/var/lib/mysql